version: '3.3'

services:
  db:
    build: db
    image: "varunlokeswaran/k8s-wordsmith-db:${BUILD_NUMBER}"

  words:
    build: words
    image: "varunlokeswaran/k8s-wordsmith-api:${BUILD_NUMBER}"
    deploy:
      replicas: 3

  web:
    build: web
    image: "varunlokeswaran/k8s-wordsmith-web:${BUILD_NUMBER}"
    ports:
     - "8080:80"