version: '3.3'

services:
  db:
    build: db
      args:
        - build_no
    image: varun-lokeswaran/k8s-wordsmith-db

  words:
    build: words
      args:
        - build_no
    image: varun-lokeswaran/k8s-wordsmith-api
    deploy:
      replicas: 5

  web:
    build: web
      args:
        - build_no
    image: varun-lokeswaran/k8s-wordsmith-web
    ports:
     - "8080:80"