version: '3.3'

services:
  db:
    build: db
    image: varun-lokeswaran/k8s-wordsmith-db:${BUILD_NUMBER}

  words:
    build: words
    image: varun-lokeswaran/k8s-wordsmith-api:${BUILD_NUMBER}
    deploy:
      replicas: 5

  web:
    build: web
    image: varun-lokeswaran/k8s-wordsmith-web:${BUILD_NUMBER}
    ports:
     - "8080:80"